clear:
  description: >
    Deletes all saved data.

delete:
  description: >
    Deletes a saved state for an entity.
  fields:
    entity_id:
      name: Entity
      description: ID of entity to delete from saver.
      example: sun.sun
      required: true
      selector:
        entity:

delete_variable:
  description: >
    Deletes a saved variable.
  fields:
    name:
      name: Variable
      description: Name of the variable to delete from saver.
      example: counter
      required: true
      selector:
        text:

execute:
  description: >
    (Deprecated) Executes a script using all saved entities and variables.
  fields:
    script:
      name: Script
      description: The script to execute using saved data.
      required: true

set_variable:
  description: >
    Sets the value to the variable.
  fields:
    name:
      name: Variable
      description: Name of the variable to save.
      example: counter
      required: true
      selector:
        text:
    value:
      name: Value
      description: The new value
      example: 3
      required: true
      selector:
        text:

save_state:
  description: >
    Saves the state and parameters of the entity.
  fields:
    entity_id:
      name: Entity
      description: ID of the entity that should be saved.
      example: sun.sun
      required: true
      selector:
        entity:

restore_state:
  description: >
    (Deprecated) Executes the script using saved state of the entity.
  fields:
    entity_id:
      name: Entity
      description: ID of the entity to restore.
      example: sun.sun
      required: true
      selector:
        entity:
    restore_script:
      name: Restore script
      description: Script used to restore values.
      required: true
    delete_after_run:
      name: Delete after run
      description: "Deletes the saved state after an execution of the script. Default: true [Optional]"
      example: false
      selector:
        boolean:
